modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "idlegenerators"
version = "${version}"
displayName = "Idle Generators"
authors = "ghozix"
description = '''
Idle resource generators: place a generator and it produces resources over real time, even while the world is closed.
'''
logoFile = "assets/idlegenerators/icon.png"

[[dependencies.idlegenerators]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.idlegenerators]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.idlegenerators]]
modId = "architectury"
type = "required"
versionRange = "[21.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.idlegenerators]]
modId = "cloth_config"
type = "required"
versionRange = "[26.2.155,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "idlegenerators.mixins.json"
